package fr.gstraymond.constants;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class KeywordAbilities {

    public static List<String> ALL = new ArrayList<>();

    // http://mtgsalvation.gamepedia.com/Keyword_ability
    static {
        Collections.addAll(ALL,
                "Deathtouch",
                "Defender",
                "Double strike",
                //"Enchant",
                "Equip",
                "First strike",
                "Flash",
                "Flying",
                "Haste",
                "Hexproof",
                "Indestructible",
                "Intimidate",
                "Landwalk",
                "Lifelink",
                "Protection",
                "Reach",
                "Shroud",
                "Trample",
                "Vigilance",
                "Banding",
                "Rampage",
                "Cumulative upkeep",
                "Flanking",
                "Phasing",
                "Buyback",
                "Shadow",
                "Cycling",
                "Echo",
                "Horsemanship",
                "Fading",
                "Kicker",
                "Flashback",
                "Madness",
                "Fear",
                "Morph",
                "Amplify",
                "Provoke",
                "Storm",
                "Affinity",
                "Entwine",
                "Modular",
                "Sunburst",
                "Bushido",
                "Soulshift",
                "Splice",
                "Offering",
                "Ninjutsu",
                "Epic",
                "Convoke",
                "Dredge",
                "Transmute",
                "Bloodthirst",
                "Haunt",
                "Replicate",
                "Forecast",
                "Graft",
                "Recover",
                "Ripple",
                "Split second",
                "Suspend",
                "Vanishing",
                "Absorb",
                "Aura swap",
                "Delve",
                "Fortify",
                "Frenzy",
                "Gravestorm",
                "Poisonous",
                "Transfigure",
                //"Champion", // FIXME
                "Changeling",
                "Evoke",
                "Hideaway",
                "Prowl",
                "Reinforce",
                "Conspire",
                "Persist",
                "Wither",
                "Retrace",
                "Devour",
                "Exalted",
                "Unearth",
                "Cascade",
                "Annihilator",
                "Level up",
                "Rebound",
                "Totem armor",
                "Infect",
                "Battle Cry",
                "Living weapon",
                "Undying",
                "Miracle",
                "Soulbond",
                "Overload",
                "Scavenge",
                "Unleash",
                "Cipher",
                "Evolve",
                "Extort",
                "Fuse",
                "Bestow",
                "Tribute",
                "Dethrone",
                "Hidden agenda",
                "Outlast",
                "Prowess",
                "Dash",
                "Exploit",
                "Menace",
                "Renown",
                "Awaken",
                "Devoid",
                "Ingest",
                "Myriad",
                "Surge",
                "Skulk",
                "Emerge",
                "Escalate",
                "Melee"
        );
    }
}
